# ?????URL
# ???jdbc:postgresql://???:??/????
database.url=jdbc:postgresql://localhost:5432/chatbot_db
# ??????
database.username=chatbot_user
# ?????
database.password=888888
# ????????????????????HikariCP?
# database.pool.size=20
#?????????
#chat_sessions (session_id,robot_id,robot_name_start_time,end_time)
#chat_messages (message_id,session_id,sender_type,message_content,timestamp)
